all: distancia driverDistancia distanciaCluster driverDistanciaCluster

distancia: distancia
	javac distancia.java
driverDistancia: driverDistancia
	javac driverDistancia.java
distanciaCluster: distanciaCluster
	javac distanciaCluster.java
driverDistanciaCluster: driverDistanciaCluster
	javac driverDistanciaCluster.java
clean:
	rm -f *.class
