all: distanciaCluster driverDistanciaCluster

distanciaCluster: distanciaCluster
	javac distanciaCluster.java
driverDistanciaCluster: driverDistanciaCluster
	javac driverDistanciaCluster.java
clean:
	rm -f *.class
