

/**
 *
 * @author gabrielcarrillolopez
 */
package interfazteclado;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

public class configurarTeclado extends javax.swing.JFrame {
	teclado tecladoEscogido = new teclado();
	Initialize init = new Initialize();
	
	/**
	 * Creates new form configurarTeclado
	 */
	
	public configurarTeclado() {
		teclado tec = new teclado();
		limpiarCampos();
		
		initComponents();
	}
	
	public void limpiarCampos() {
		this.jtColumnas.setText("");
		this.jtFilas.setText("");
		this.jtPosiciones.setText("");
		this.lbMens.setText("");
		//this.lbMens.setVisible(false);
	}
	
	public void inicializar() {	//limpiar todos los campos al cargar
		limpiarCampos();
	}
	
	configurarTeclado(Initialize init) {
		this.init = init;
		
		initComponents();
		//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        btAtras = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        lbMens = new javax.swing.JLabel();
        lbFilas = new javax.swing.JLabel();
        lbColumnas = new javax.swing.JLabel();
        lbPosiciones = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbFormaTeclado = new javax.swing.JLabel();
        jtFilas = new javax.swing.JTextField();
        jtColumnas = new javax.swing.JTextField();
        jtPosiciones = new javax.swing.JTextField();
        btResetValores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setText("Editar teclado:");

        btAtras.setText("Atrás");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        lbMens.setBackground(new java.awt.Color(255, 51, 51));
        lbMens.setText("jLabel1");
        lbMens.setBorder(new javax.swing.border.MatteBorder(null));
        lbMens.setOpaque(true);

        lbFilas.setText("Filas:");

        lbColumnas.setText("Columnas:");

        lbPosiciones.setText("Posiciones:");

        jLabel4.setText("Lados teclas:");

        lbFormaTeclado.setText("Forma Teclado:");

        jtFilas.setText("jTextField1");

        jtColumnas.setText("jTextField1");

        jtPosiciones.setText("jTextField1");
        jtPosiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPosicionesActionPerformed(evt);
            }
        });

        btResetValores.setText("Reset Valores");
        btResetValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetValoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lbFormaTeclado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbPosiciones)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbFilas)
                                    .addComponent(lbColumnas))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtColumnas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jtFilas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jtPosiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMens, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAtras)
                                .addGap(18, 18, 18)
                                .addComponent(btGuardar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btResetValores, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFilas)
                    .addComponent(jtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbColumnas)
                    .addComponent(jtColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPosiciones)
                    .addComponent(jtPosiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFormaTeclado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btResetValores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMens)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAtras)
                    .addComponent(btGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPosicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPosicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPosicionesActionPerformed

    private void btResetValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetValoresActionPerformed
        limpiarCampos();
		
    }//GEN-LAST:event_btResetValoresActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        try {
			int columnas = Integer.parseInt(this.jtColumnas.getText());
			int filas = Integer.parseInt(this.jtFilas.getText());
			int posiciones = Integer.parseInt(this.jtPosiciones.getText());
			
			teclado tec = new teclado(forma, filas, columnas, posiciones, lados);
			limpiarCampos();
			
			this.lbMens.setText("Teclado guardado");

		} catch (Exception e) {
			this.lbMens.setText("Error de guardado");
		}
    }//GEN-LAST:event_btGuardarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(configurarTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(configurarTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(configurarTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(configurarTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new configurarTeclado().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtras;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btResetValores;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtColumnas;
    private javax.swing.JTextField jtFilas;
    private javax.swing.JTextField jtPosiciones;
    private javax.swing.JLabel lbColumnas;
    private javax.swing.JLabel lbFilas;
    private javax.swing.JLabel lbFormaTeclado;
    private javax.swing.JLabel lbMens;
    private javax.swing.JLabel lbPosiciones;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
