/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfazteclado;

/**
 *
 * @author gabrielcarrillolopez
 */
public class Initialize extends javax.swing.JFrame {

	/**
	 * Creates new form Initialize
	 */
    
    teclado tec = new teclado();
    
	
	
	public Initialize() {
		
		initComponents();
	}
        
        public void recibirTeclado(teclado tec) {
            this.tec = tec;
        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        btVisualizacion = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAlfabeto = new javax.swing.JMenu();
        mnCjtoTextos = new javax.swing.JMenu();
        mnTecla = new javax.swing.JMenu();
        mnTeclado = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setText("giTeclado");

        btVisualizacion.setBackground(new java.awt.Color(0, 204, 51));
        btVisualizacion.setText("VISUALIZACIÓN");
        btVisualizacion.setOpaque(true);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        mnAlfabeto.setText("ALFABETO");
        mnAlfabeto.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnAlfabetoMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenuBar1.add(mnAlfabeto);

        mnCjtoTextos.setText("CJTO TEXTOS");
        mnCjtoTextos.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnCjtoTextosMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenuBar1.add(mnCjtoTextos);

        mnTecla.setText("TECLA");
        mnTecla.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnTeclaMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenuBar1.add(mnTecla);

        mnTeclado.setText("TECLADO");
        mnTeclado.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnTecladoMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        mnTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTecladoActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnTeclado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(62, 62, 62)
                .addComponent(btVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btSalir)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTecladoActionPerformed
		//no ha de hacer nada
    }//GEN-LAST:event_mnTecladoActionPerformed

    private void mnTecladoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnTecladoMenuSelected
   		Initialize.this.setVisible(false);
		configurarTeclado confTeclado = new configurarTeclado(Initialize.this, tec);
		confTeclado.setVisible(true);
    }//GEN-LAST:event_mnTecladoMenuSelected

    private void mnTeclaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnTeclaMenuSelected
        /*Initialize.this.setVisible(false);
		configurarTecla confTecla = new configurarTecla();
		confTecla.setVisible(true);*/
    }//GEN-LAST:event_mnTeclaMenuSelected

    private void mnCjtoTextosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnCjtoTextosMenuSelected
        Initialize.this.setVisible(false);
		configurarCTextos confCT = new configurarCTextos();
		confCT.setVisible(true);
    }//GEN-LAST:event_mnCjtoTextosMenuSelected

    private void mnAlfabetoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnAlfabetoMenuSelected
        Initialize.this.setVisible(false);
		configurarAlfabeto confAlf = new configurarAlfabeto();
		confAlf.setVisible(true);
    }//GEN-LAST:event_mnAlfabetoMenuSelected

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSalirActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Initialize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Initialize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Initialize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Initialize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Initialize().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btVisualizacion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenu mnAlfabeto;
    private javax.swing.JMenu mnCjtoTextos;
    private javax.swing.JMenu mnTecla;
    private javax.swing.JMenu mnTeclado;
    // End of variables declaration//GEN-END:variables
}
